# todo: 프로파일 별 분리 필요 prod/dev/local

logging:
  level:
    # 동네 인증 기반 디버깅을 위해 해당 서비스 로직에 대해서만 임시로 Logging level 을 debug 로 적용. 추후 원복 필요
    com.numberone.daepiro.domain.community.service.UserAddressVerifiedService: DEBUG

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      # todo: 릴리즈 된 이후에 update -> none 으로 변경 필요
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  config:
    import: 'aws-secretsmanager:daepiro'

springdoc:
  api-docs:
    path: /api-docs  # API 문서의 기본 경로 설정
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 경로 설정
    operationsSorter: method  # 메서드 정렬 (get, post 순)
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expire: ${JWT_ACCESS_TOKEN_EXPIRE}
  refresh-token-expire: ${JWT_REFRESH_TOKEN_EXPIRE}
  admin-token-expire: ${JWT_ADMIN_TOKEN_EXPIRE}
kakao:
  base-url: ${KAKAO_BASE_URL}
  token-info-url: ${KAKAO_TOKEN_INFO_URL}
  local-api-url: ${KAKAO_LOCAL_API_URL}
  client-id: ${KAKAO_CLIENT_ID}
naver:
  base-url: ${NAVER_BASE_URL}
  token-info-url: ${NAVER_TOKEN_INFO_URL}
apple:
  base-url: ${APPLE_BASE_URL}
  client-id: ${APPLE_CLIENT_ID}
  team-id: ${APPLE_TEAM_ID}
  key-id: ${APPLE_KEY_ID}
  private-key: ${APPLE_PRIVATE_KEY}
  redirect-uri: ${APPLE_REDIRECT_URI}
  grant-type: ${APPLE_GRANT_TYPE}
fcm:
  json: ${FIREBASE_JSON}

s3:
  credentials:
    access: ${S3_ACCESS_KEY}
    secret: ${S3_SECRET_KEY}
  bucket: ${S3_BUCKET}
  region: ap-northeast-2



